#!/usr/bin/env python3

import sys
import logging

## Logging
log = logging.getLogger(__name__)

def translate_dna(sequence):
    """Translate DNA to Protein."""
    # Standard genetic code
    gencode = {
        'ATA':'I', 'ATC':'I', 'ATT':'I', 'ATG':'M',
        'ACA':'T', 'ACC':'T', 'ACG':'T', 'ACT':'T',
        'AAC':'N', 'AAT':'N', 'AAA':'K', 'AAG':'K',
        'AGC':'S', 'AGT':'S', 'AGA':'R', 'AGG':'R',
        'CTA':'L', 'CTC':'L', 'CTG':'L', 'CTT':'L',
        'CCA':'P', 'CCC':'P', 'CCG':'P', 'CCT':'P',
        'CAC':'H', 'CAT':'H', 'CAA':'Q', 'CAG':'Q',
        'CGA':'R', 'CGC':'R', 'CGG':'R', 'CGT':'R',
        'GTA':'V', 'GTC':'V', 'GTG':'V', 'GTT':'V',
        'GCA':'A', 'GCC':'A', 'GCG':'A', 'GCT':'A',
        'GAC':'D', 'GAT':'D', 'GAA':'E', 'GAG':'E',
        'GGA':'G', 'GGC':'G', 'GGG':'G', 'GGT':'G',
        'TCA':'S', 'TCC':'S', 'TCG':'S', 'TCT':'S',
        'TTC':'F', 'TTT':'F', 'TTA':'L', 'TTG':'L',
        'TAC':'Y', 'TAT':'Y', 'TAA':'*', 'TAG':'*',
        'TGC':'C', 'TGT':'C', 'TGA':'*', 'TGG':'W',
    }

    sequence = sequence.upper()
    protein = []
    n_ambiguous = 0
    ## Only translate full codons
    for i in range(0, len(sequence) - len(sequence) % 3, 3):
        codon = sequence[i:i+3]
        ## A gap codon must stay a gap.
        if set(codon) <= set('-.'):
            protein.append('-')
        elif 'N' in codon or '!' in codon:
            protein.append('X')
            n_ambiguous += 1
        else:
            protein.append(gencode.get(codon, 'X'))
    if n_ambiguous:
        log.info(f"masked {n_ambiguous} ambiguous codon(s) to X")
    return "".join(protein)


def read_fasta(filepath):
    """Read a regular fasta file and return a dictionary mapping header to sequence."""
    sequences = {}
    header = None
    seq = []
    with open(filepath, 'r') as f:
        for line in f:
            line = line.strip()
            if line.startswith(">"):
                if header:
                    sequences[header] = "".join(seq)
                header = line[1:] # Strip '>'
                seq = []
            elif line:
                seq.append(line)
        if header:
            sequences[header] = "".join(seq)
    return sequences


def main():
    in_alignment = snakemake.input[0]
    out_alignment = snakemake.output[0]
    logging.basicConfig(
        filemode="w",
        level=logging.DEBUG,
        format="[%(levelname)s] %(message)s",
    )

    log.info("=== translate codon nt alignment to amino acid alignment ===")
    log.info("Input alignment : %s", in_alignment)
    log.info("Output alignment  : %s", out_alignment)
    
    # Read the masked.fa generated by codonify (pure nt aligners will likely produce faulty frameshifts)
    log.info(f"Reading {in_alignment}...")
    try:
        codon_sequences = read_fasta(in_alignment)
    except FileNotFoundError:
        log.critical(f"Error: Could not find input file {in_alignment}")
        sys.exit(1)

    all_results_protein = {}
    total_queries = len(codon_sequences)

    # enumerate returns (index, (key, value))
    for i, (query, sequence) in enumerate(codon_sequences.items(), start=1):

        log.info(f"Processing query: {query}, {i}/{total_queries}")
        
        ## Clean the sequence (remove N and dashes) and translate
        ## Added .replace("!", "N") to accomodate macse2
        
        if len(sequence) % 3 != 0:
            log.warning(f"Warning: Clean DNA for {query} is not mod 3 length ({len(sequence)}). Translation might be truncated.")
            
        all_results_protein[query] = translate_dna(sequence)
        
            
    # Write all consolidated results at the end
    out_file = out_alignment
    if all_results_protein:
        log.info(f"\nSaving consolidated statistics to {out_file}")
        with open(out_file, "w") as f:
            for query, sequence in all_results_protein.items():
                f.write(">" + query + "\n")
                f.write(sequence + "\n")
    else:
        log.critical("\nNo valid overall results found.")
        sys.exit(1)


if __name__ == "__main__":
    main()
